[package]
name = "html-prettify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html-parser = {path = "../html-parser"}
argparse = "0.2.2"