cargo-features = ["per-package-target"]

[workspace]
members = ["deps/pico-args", "bench", "deps/simplelog", "deps/log", "deps/termcolor", "css-parser", "html-parser", "dds", "dds-api", "deps/indextree"]
default-members = ["bench", "css-parser", "html-parser", "dds", "dds-api"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1