cargo-features = ["per-package-target"]

[workspace]
members = ["bench", "simplelog", "log", "termcolor", "css-parser", "html-parser", "dds", "dds-api", "indextree"]
default-members = ["bench", "simplelog", "log", "termcolor", "css-parser", "html-parser", "dds", "dds-api","indextree"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1