cargo-features = ["per-package-target"]

[workspace]
members = ["dds-rust-example", "dds-core", "dds-parser", "dds-wasm-api"]
default-members = ["dds-rust-example", "dds-core", "dds-parser", "dds-wasm-api"]