cargo-features = ["per-package-target"]

[workspace]
members = ["simplelog", "log", "termcolor", "css-parser", "html-parser", "dds", "indextree"]
default-members = ["simplelog", "log", "termcolor", "css-parser", "html-parser", "dds", "indextree"]

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1