[package]
name = "dds-core"
version = "0.1.0"
edition = "2021"
default-run = "dds-core"

[dependencies]
html-parser = { path = "../html-parser" }

[dependencies.wasmi]
version = "*"
default-features = false
features = ["core"]